"""add_ai_threads_ai_messages

Revision ID: d3339fc62797
Revises: 202605131530
Create Date: 2026-05-27 18:15:36.884894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3339fc62797'
down_revision: Union[str, Sequence[str], None] = '202605131530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_threads_created_by'), 'ai_threads', ['created_by'], unique=False)
    op.create_index(op.f('ix_ai_threads_workspace_id'), 'ai_threads', ['workspace_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'tool')", name='ai_messages_role_check'),
    sa.ForeignKeyConstraint(['thread_id'], ['ai_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_messages_thread_created', 'ai_messages', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_thread_id'), 'ai_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_messages_thread_id'), table_name='ai_messages')
    op.drop_index('idx_ai_messages_thread_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_ai_threads_workspace_id'), table_name='ai_threads')
    op.drop_index(op.f('ix_ai_threads_created_by'), table_name='ai_threads')
    op.drop_table('ai_threads')
    # ### end Alembic commands ###
